### ISSUE TITLE
Table Joins - Field Type Conversion

### ISSUE THREAD

**Issue by jj0hns0n** [jj0hns0n/geonode#29]
csvkit is a little too smart about casting strings like 000200 to an integer and creating fields with type integer if it encounters these. We need it to leave them as strings and not trim the leading zeroes.

This can lead to failed joins due to field type mismatch.

**Comment by raprasad** [comment]
I'll try steps listed in #30.

**Comment by jj0hns0n** [comment]
Closing as a dupe of #40 which has more info.
