### ISSUE TITLE
Map CSV with Lat/Lng columns

### ISSUE THREAD

**Issue by raprasad** [jj0hns0n/geonode#32]
### Some questions
- What latitude, longitude formats are acceptable?
- What, if any, conversions should be done?
   - Convert before calling API (on Dataverse side)?
   - Include converter on GeoNode/WorldMap side?

**Comment by blewis** [comment]
must be decimal degrees.

**Comment by raprasad** [comment]
This is a new endpoint.  Attributes would be:

- title
- abstract
- csv file (the file itself)
- latitude column (on csv file)
- longitude column (on csv file)

/cc @blewis @jj0hns0n

**Comment by jj0hns0n** [comment]
Implemented at https://github.com/jj0hns0n/geonode/commit/7af416152f17087bfa3a2d372d20a357461ef709 ... This can probably use some more work and more error handling, but the basics are in place now.
