### ISSUE TITLE
Data processing: pre API call

### ISSUE THREAD

**Issue by raprasad** [jj0hns0n/geonode#34]
FIPS Example
- CSV file has FIPS county in 2 columns: 
     - state column (2 digits)
     - county column (3 digits)
- Pre-API call processing (@raprasad)
     - User specifies 2 columns as being the FIPS county
     - Additional column created for join purposes
- API call
     - csv upload:  file has newly combined FIPS column
     - join: specify new column for join

**Comment by blewis** [comment]
Handled by #49

**Comment by jj0hns0n** [comment]
Close as dupe of #49
