### ISSUE TITLE
Implement jointarget api endpoint filtering

### ISSUE THREAD

**Issue by jj0hns0n** [jj0hns0n/geonode#43]
The jointarget endpoint should allow for filtering of the results (now it returns _everything_). The following are potential types of filters but there may be others.

* [ ] By Category
* [ ] By Layer Name/Title/Description
* [ ] By Year (New field on JoinTarget)

**Comment by raprasad** [comment]
Spoke with Ben earlier.  
He'd also like a "year" (4-digits) on the Join Target.

**Comment by jj0hns0n** [comment]
Added at https://github.com/jj0hns0n/geonode/commit/25f852d2c21509c9422f221523e41e807bc6d313

Year added to the JoinTarget. You can now filter by

* title = case insensitive icontains on layer title
* type = case insensitve icontains on geocode_type
* start_year = year greater than or equal to
* end_year = year less than or equal to

http://23.23.180.177/datatables/api/jointargets?title=tract&type=tract&start_year=2013&end_year=2013

Minimal error handling added.
