### ISSUE TITLE
Store join stats and return via API

### ISSUE THREAD

**Issue by jj0hns0n** [jj0hns0n/geonode#48]
We need to record the statistics for the join (how many matched and unmatched records as well as list of unmatched records) and return this via the API.

**Comment by raprasad** [comment]
Can we return failed rows to user.

**Comment by jj0hns0n** [comment]
Yes, lets include a (potentially truncated) list of rows that _dont_ match.

**Comment by blewis** [comment]
Let's make loading this report and truncated list to GeoNode metadata abstract a possible Phase II enhancement.

**Comment by blewis** [comment]
Also perhaps now we need to load date, title, abstract to metadata in worldmap.

**Comment by raprasad** [comment]
- [ ] potentially store basic stats on the TableJoin model? If too much, move to later phase
     - e.g. TextField with JSON/python dict.    
```javascript
{ "datatable_rows" : 100, "rows_joined" : 98, "rows_failed": 2, "failed_row_detail"  : "--maybe-later--"}
```
